"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-09-26 09:13:18.709063+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('kind', sa.Enum('PRODUCT', 'PROJECT', 'RELATED', name='basket_kind_enum'), nullable=False),
    sa.Column('title_fa', sa.String(length=200), nullable=True),
    sa.Column('owner_token', sa.String(length=64), nullable=False),
    sa.Column('intent_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_budget', sa.Integer(), nullable=True),
    sa.Column('notes_fa', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('SEED', 'CRAWL', 'MANUAL', name='data_source_enum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baskets'))
    )
    op.create_index(op.f('ix_baskets_owner_token'), 'baskets', ['owner_token'], unique=False)
    op.create_table('brands',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_fa', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_fa', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.Enum('BATHROOM', 'KITCHEN', name='domain_enum'), nullable=False),
    sa.Column('kind', sa.Enum('FIXTURE', 'SURFACE', 'ACCESSORY', 'MATERIAL', 'APPLIANCE', 'LIGHTING', 'HARDWARE', name='category_kind_enum'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('description_fa', sa.Text(), nullable=True),
    sa.Column('search_text', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_domain'), 'categories', ['domain'], unique=False)
    op.create_index(op.f('ix_categories_kind'), 'categories', ['kind'], unique=False)
    op.create_index(op.f('ix_categories_search_text'), 'categories', ['search_text'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('project_templates',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_fa', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.Enum('BATHROOM', 'KITCHEN', name='domain_enum'), nullable=False),
    sa.Column('project_type', sa.Enum('RENOVATION', 'NEW_BUILD', 'REDESIGN', 'REPAIR', name='project_type_enum'), nullable=False),
    sa.Column('description_fa', sa.Text(), nullable=True),
    sa.Column('keywords_fa', sa.Text(), nullable=False),
    sa.Column('default_area_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('default_quality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'ULTRA', name='quality_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_templates'))
    )
    op.create_index(op.f('ix_project_templates_domain'), 'project_templates', ['domain'], unique=False)
    op.create_index(op.f('ix_project_templates_project_type'), 'project_templates', ['project_type'], unique=False)
    op.create_index(op.f('ix_project_templates_slug'), 'project_templates', ['slug'], unique=True)
    op.create_table('sellers',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_fa', sa.String(length=140), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('description_fa', sa.String(length=300), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sellers'))
    )
    op.create_index(op.f('ix_sellers_slug'), 'sellers', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name_fa', sa.String(length=200), nullable=False),
    sa.Column('subtitle_fa', sa.String(length=240), nullable=True),
    sa.Column('description_fa', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.Enum('BATHROOM', 'KITCHEN', name='domain_enum'), nullable=False),
    sa.Column('quality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'ULTRA', name='quality_enum'), nullable=False),
    sa.Column('style', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('reference_price', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('origin_country', sa.String(length=80), nullable=True),
    sa.Column('search_text', sa.String(length=900), nullable=False),
    sa.Column('data_source', sa.Enum('SEED', 'CRAWL', 'MANUAL', name='data_source_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_category_quality', 'products', ['category_id', 'quality'], unique=False)
    op.create_index(op.f('ix_products_domain'), 'products', ['domain'], unique=False)
    op.create_index('ix_products_domain_quality', 'products', ['domain', 'quality'], unique=False)
    op.create_index(op.f('ix_products_search_text'), 'products', ['search_text'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('project_analyses',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('basket_id', sa.Uuid(), nullable=True),
    sa.Column('title_fa', sa.String(length=200), nullable=False),
    sa.Column('original_query', sa.Text(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('quality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'ULTRA', name='quality_enum'), nullable=False),
    sa.Column('style', sa.String(length=40), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intent_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_total', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('interpreter', sa.String(length=40), nullable=False),
    sa.Column('data_source', sa.Enum('SEED', 'CRAWL', 'MANUAL', name='data_source_enum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_project_analyses_basket_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], name=op.f('fk_project_analyses_template_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_analyses')),
    sa.UniqueConstraint('basket_id', name=op.f('uq_project_analyses_basket_id'))
    )
    op.create_index(op.f('ix_project_analyses_template_id'), 'project_analyses', ['template_id'], unique=False)
    op.create_table('project_requirements',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_mode', sa.Enum('PER_AREA', 'FIXED', name='quantity_mode_enum'), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quality_min', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'ULTRA', name='quality_enum'), nullable=False),
    sa.Column('style', sa.String(length=40), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('reason_fa', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_project_requirements_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['project_templates.id'], name=op.f('fk_project_requirements_template_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_requirements')),
    sa.UniqueConstraint('template_id', 'role', name='uq_requirement_template_role')
    )
    op.create_index(op.f('ix_project_requirements_category_id'), 'project_requirements', ['category_id'], unique=False)
    op.create_index(op.f('ix_project_requirements_role'), 'project_requirements', ['role'], unique=False)
    op.create_index(op.f('ix_project_requirements_template_id'), 'project_requirements', ['template_id'], unique=False)
    op.create_table('offers',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Enum('IN_STOCK', 'LOW_STOCK', 'PREORDER', 'OUT_OF_STOCK', name='availability_enum'), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.Enum('SEED', 'CRAWL', 'MANUAL', name='data_source_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_offers_product_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_offers_seller_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('product_id', 'seller_id', name='uq_offer_product_seller')
    )
    op.create_index(op.f('ix_offers_availability'), 'offers', ['availability'], unique=False)
    op.create_index(op.f('ix_offers_product_id'), 'offers', ['product_id'], unique=False)
    op.create_index('ix_offers_product_price', 'offers', ['product_id', 'price'], unique=False)
    op.create_index(op.f('ix_offers_seller_id'), 'offers', ['seller_id'], unique=False)
    op.create_index('ix_offers_seller_product', 'offers', ['seller_id', 'product_id'], unique=False)
    op.create_table('product_attributes',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label_fa', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=240), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_attributes_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_attributes')),
    sa.UniqueConstraint('product_id', 'key', name='uq_product_attribute_key')
    )
    op.create_index(op.f('ix_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)
    op.create_table('product_relations',
    sa.Column('source_product_id', sa.Uuid(), nullable=False),
    sa.Column('target_product_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Enum('INSTALL_KIT', 'COMPATIBLE_FITTING', 'REQUIRED_MATERIAL', 'ACCESSORY_PAIR', 'ROOM_PAIR', 'ALTERNATIVE', name='relation_type_enum'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason_fa', sa.String(length=300), nullable=False),
    sa.Column('data_source', sa.Enum('SEED', 'CRAWL', 'MANUAL', name='data_source_enum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], name=op.f('fk_product_relations_source_product_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], name=op.f('fk_product_relations_target_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_relations')),
    sa.UniqueConstraint('source_product_id', 'target_product_id', 'relation_type', name='uq_product_relation')
    )
    op.create_index(op.f('ix_product_relations_relation_type'), 'product_relations', ['relation_type'], unique=False)
    op.create_index('ix_product_relations_source', 'product_relations', ['source_product_id', 'weight'], unique=False)
    op.create_index(op.f('ix_product_relations_source_product_id'), 'product_relations', ['source_product_id'], unique=False)
    op.create_index(op.f('ix_product_relations_target_product_id'), 'product_relations', ['target_product_id'], unique=False)
    op.create_table('basket_items',
    sa.Column('basket_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('origin', sa.Enum('SEARCH', 'PROJECT', 'RELATED', 'OPTIMIZATION', 'MANUAL', name='item_origin_enum'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('reason_fa', sa.String(length=300), nullable=True),
    sa.Column('replaced_item_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_basket_items_basket_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_basket_items_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_basket_items_offer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_basket_items_product_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_item_id'], ['basket_items.id'], name=op.f('fk_basket_items_replaced_item_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket_items')),
    sa.UniqueConstraint('basket_id', 'product_id', 'role', name='uq_basket_item_product_role')
    )
    op.create_index(op.f('ix_basket_items_basket_id'), 'basket_items', ['basket_id'], unique=False)
    op.create_index(op.f('ix_basket_items_offer_id'), 'basket_items', ['offer_id'], unique=False)
    op.create_index(op.f('ix_basket_items_product_id'), 'basket_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basket_items_product_id'), table_name='basket_items')
    op.drop_index(op.f('ix_basket_items_offer_id'), table_name='basket_items')
    op.drop_index(op.f('ix_basket_items_basket_id'), table_name='basket_items')
    op.drop_table('basket_items')
    op.drop_index(op.f('ix_product_relations_target_product_id'), table_name='product_relations')
    op.drop_index(op.f('ix_product_relations_source_product_id'), table_name='product_relations')
    op.drop_index('ix_product_relations_source', table_name='product_relations')
    op.drop_index(op.f('ix_product_relations_relation_type'), table_name='product_relations')
    op.drop_table('product_relations')
    op.drop_index(op.f('ix_product_attributes_product_id'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index('ix_offers_seller_product', table_name='offers')
    op.drop_index(op.f('ix_offers_seller_id'), table_name='offers')
    op.drop_index('ix_offers_product_price', table_name='offers')
    op.drop_index(op.f('ix_offers_product_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_availability'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_project_requirements_template_id'), table_name='project_requirements')
    op.drop_index(op.f('ix_project_requirements_role'), table_name='project_requirements')
    op.drop_index(op.f('ix_project_requirements_category_id'), table_name='project_requirements')
    op.drop_table('project_requirements')
    op.drop_index(op.f('ix_project_analyses_template_id'), table_name='project_analyses')
    op.drop_table('project_analyses')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_search_text'), table_name='products')
    op.drop_index('ix_products_domain_quality', table_name='products')
    op.drop_index(op.f('ix_products_domain'), table_name='products')
    op.drop_index('ix_products_category_quality', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_sellers_slug'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_project_templates_slug'), table_name='project_templates')
    op.drop_index(op.f('ix_project_templates_project_type'), table_name='project_templates')
    op.drop_index(op.f('ix_project_templates_domain'), table_name='project_templates')
    op.drop_table('project_templates')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_search_text'), table_name='categories')
    op.drop_index(op.f('ix_categories_kind'), table_name='categories')
    op.drop_index(op.f('ix_categories_domain'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_baskets_owner_token'), table_name='baskets')
    op.drop_table('baskets')
    # ### end Alembic commands ###
